--drop table IF exists carts,user_roles,users,roles,authors,books,items,orders;
CREATE TABLE IF NOT EXISTS roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
  username VARCHAR(255) NOT NULL UNIQUE,
  role_id BIGINT,
  CONSTRAINT fk_users_to_role_id FOREIGN KEY(role_id) REFERENCES roles(id),
  CONSTRAINT pk_user PRIMARY KEY (id)
);

 CREATE TABLE IF NOT EXISTS authors (
         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
         name VARCHAR(255) NOT NULL,
         CONSTRAINT pk_authors PRIMARY KEY (id)
        );
 CREATE TABLE IF NOT EXISTS books (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          name VARCHAR NOT NULL,
          author_id BIGINT NOT NULL,
          image VARCHAR NOT NULL,
          lang VARCHAR,
          release_date TIMESTAMP NOT NULL,
          description VARCHAR,
          genre VARCHAR,
          pages BIGINT,
          rating INTEGER,
          book_is_new BOOLEAN,
          price INTEGER,
          amount BIGINT,
          CONSTRAINT fk_books_to_authors FOREIGN KEY(author_id) REFERENCES authors(id),
          CONSTRAINT pk_books PRIMARY KEY (id)
         );
 CREATE TABLE IF NOT EXISTS carts (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          book_id BIGINT NOT NULL,
          user_id BIGINT NOT NULL,
          quantity BIGINT NOT NULL,
          CONSTRAINT fk_carts_to_books FOREIGN KEY(book_id) REFERENCES books(id) ON DELETE CASCADE,
          CONSTRAINT fk_carts_to_users FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE ,
          CONSTRAINT pk_carts PRIMARY KEY (id)
         );
 CREATE TABLE IF NOT EXISTS orders (
                   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                   order_date TIMESTAMP NOT NULL,
                   user_id BIGINT NOT NULL,
                   CONSTRAINT fk_orders_to_users FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE ,
                   CONSTRAINT pk_orders PRIMARY KEY (id));
 CREATE TABLE IF NOT EXISTS items (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          book_id BIGINT NOT NULL,
          quantity BIGINT NOT NULL,
          order_id BIGINT NOT NULL,
          CONSTRAINT fk_items_to_book FOREIGN KEY(book_id) REFERENCES books(id) ON DELETE CASCADE,
          CONSTRAINT fk_items_to_order FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,
          CONSTRAINT pk_items PRIMARY KEY (id)
         );

